# This is a basic workflow to help you get started with Actions

name: Master2Dev

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_dispatch:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
#         with:
#           fetch-depth: 200

      - name: Merge master to dev
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git fetch origin dev
          git fetch origin master
          
          git checkout dev
          git merge origin/master -m "Merging master to dev"
          git push origin dev
